import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import "./globals.css";

export const metadata: Metadata = {
  title: "Financieel App",
  description: "Overzicht van inkomsten en uitgaven",
>>>>>>> 605c7241305da74cc13f97e1040dd3e71abc0667
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
=======
    <html lang="nl">
      <body>{children}</body>
    </html>
  );
}
>>>>>>> 605c7241305da74cc13f97e1040dd3e71abc0667
